# fly.toml app configuration file generated for donkeys on 2023-06-20T17:16:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "donkeys"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
